version: '3.7'
services:
  api:
    image: ghcr.io/sanjay812/task-tracker:v1
    container_name: task-tracker
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_db:5432/postgres
    depends_on:
      - postgres_db
      - node-exporter
      - otel-collector
  postgres_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"     # OTLP gRPC
      - "8888:8888"     # Prometheus metrics endpoint
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - tempo
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
  
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"       # Tempo querier HTTP
    command:
      - -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./tempo-config.yml:/etc/tempo/tempo.yml:ro
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/loki-config.yml
      - -target=all
    user: "10001:10001"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - ./loki-data:/loki
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    command:
      - -config.file=/etc/mimir/mimir-config.yml
      - -target=all
    ports:
      - "9009:9009"
    volumes:
      - ./mimir-config.yml:/etc/mimir/mimir-config.yml:ro
      - ./mimir-data:/var/mimir

volumes:
  pg_data:
  grafana-storage:
