receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http: 
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['node-exporter:9100']  # Adjust if Node Exporter runs elsewhere
        - job_name: 'app'
          static_configs:
            - targets: ['task-tracker:8000']  # Your app metrics endpoint

processors:
  batch:

exporters:
  debug:
    verbosity: basic
  otlphttp:
    traces_endpoint: http://tempo:4316/v1/traces
    logs_endpoint: http://loki:3100/otlp/v1/logs
    metrics_endpoint: http://mimir:9009/otlp/v1/metrics
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlphttp]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
