server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc: 
          endpoint: 0.0.0.0:4315
        http: 
          endpoint: 0.0.0.0:4316

storage:
  trace:
    backend: s3
    s3:
      bucket: "${S3_BUCKET}"
      endpoint: s3.amazonaws.com
      region: ap-south-1
      access_key: "${S3_ACCESS_KEY}"
      secret_key: "${S3_SECRET_KEY}"
      insecure: false

compactor:
  compaction:
    compaction_window: 1m
