server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc: 
          endpoint: 0.0.0.0:4315
        http: 
          endpoint: 0.0.0.0:4316

storage:
  trace:
    backend: s3
    s3:
      bucket: "my-tf-logs-66cec2cd"
      endpoint: s3.amazonaws.com
      region: ap-south-1
      access_key_id: "AKIAUG5NCPGIKCGYVUBI"
      secret_access_key: "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"
      insecure: false

compactor:
  compaction:
    compaction_window: 1m
