name: Docker Image CI
on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
   ##EC2
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        cp pem/key-rsa.pem ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        # Disable strict host key checking to avoid host verification failure in CI
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: Copy YML files to EC2
      run: |
        scp -i ~/.ssh/id_rsa yml/*.yml ubuntu@3.108.64.74:/home/ubuntu/deployments/

    - name: Connect to EC2 and run docker-compose
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.108.64.74 << 'EOF'
          if ! sudo docker version &> /dev/null
          then
              echo "Docker not found. Installing..."
              sudo apt-get install docker.io     
          else
              echo "Docker is already installed."
          fi   
          # Check Docker Compose 
          if ! sudo docker compose version &> /dev/null
          then
              echo "Docker Compose not found. Installing..."
              sudo apt-get install docker-compose-plugin -y
          else
              echo "Docker Compose is already installed."
          fi
          
          # Start and enable Docker
          
          echo "Starting Docker..."
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo systemctl status docker --no-pager
          cd /home/ubuntu/deployments
          sudo mkdir -p ./loki-data
          sudo chown -R 10001:10001 ./loki-data
          sudo docker compose up -d
        EOF
    
        
