name: Docker Image CI
on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
   ##EC2
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        cp pem/my-terraform-key.pem ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        # Disable strict host key checking to avoid host verification failure in CI
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: Copy YML files to EC2
      run: |
        scp -i ~/.ssh/id_rsa yml/*.yml ubuntu@13.201.128.15:/home/ubuntu/deployments/

    - name: Connect to EC2 and run docker-compose
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@13.201.128.15 << 'EOF'
          if ! sudo docker version &> /dev/null
          then
              echo "Docker not found. Installing..."
              # Update apt and install prerequisite packages
              sudo apt-get update -y
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              
              # Add Docker's official GPG key
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              
              # Add Docker apt repository
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              
              # Update apt again to include Docker repo packages
              sudo apt-get update -y
              
              # Install Docker Engine, CLI, containerd, and Docker Compose plugin
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  
          else
              echo "Docker is already installed."
          fi   
          # Check Docker Compose 
          if ! sudo docker compose version &> /dev/null
          then
              echo "Docker Compose not found. Installing..."
              sudo apt-get install docker-compose-plugin -y
          else
              echo "Docker Compose is already installed."
          fi
          
          # Start and enable Docker
          
          echo "Starting Docker..."
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo systemctl status docker --no-pager
          echo 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 | sudo docker login ghcr.io -u sanjay812 --password-stdin
          cd /home/ubuntu/deployments
          sudo mkdir -p ./loki-data
          sudo chown -R 10001:10001 ./loki-data
          sudo docker compose up -d
        EOF
    
        
