name: Docker Image CI
on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: start db
      run: docker run -d --name task-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=posotgres -p 5432:5432 postgres:15
    - name: Set env for tests
      run: echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres" >> $GITHUB_ENV
    # Run tests
    - name: Run unit tests
      run: |
        PYTHONPATH=. pytest -v --maxfail=1 --disable-warnings
