name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
          
    - name: Use Terraform outputs from secrets
      env:
        EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
        S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY: ${{ secrets.IAM_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
      run: |
        echo "EC2 IP: $EC2_IP"
        echo "S3 Bucket: $S3_BUCKET"
       
        # Loop over all YAML files and replace placeholders
        for f in yml/*.yml; do
          safe_bucket=$(printf '%s\n' "$S3_BUCKET" | sed 's/[&/\]/\\&/g')
          safe_access=$(printf '%s\n' "$AWS_ACCESS_KEY" | sed 's/[&/\]/\\&/g')
          safe_secret=$(printf '%s\n' "$AWS_SECRET_KEY" | sed 's/[&/\]/\\&/g')
        
          sed -i \
            -e "s|\${{ secrets.S3_BUCKET }}|$safe_bucket|g" \
            -e "s|\${{ secrets.S3_ACCESS_KEY }}|$safe_access|g" \
            -e "s|\${{ secrets.S3_SECRET_KEY }}|$safe_secret|g" "$f"
        done

        cat yml/loki-config.yml
