name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
          
    - name: Use Terraform outputs from secrets
      env:
        EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
        S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        S3_ACCESS_KEY: ${{ secrets.IAM_ACCESS_KEY_ID }}
        S3_SECRET_KEY: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
      run: |
        echo "EC2 IP: $EC2_IP"
        echo "S3 Bucket: $S3_BUCKET"
       
        for f in yml/*.yml; do envsubst < "$f" > "$f.tmp" && mv "$f.tmp" "$f"; done

        cat yml/tempo-config.yml
        cat yml/mimir-config.yml
        cat yml/loki-config.yml
