name: Terraform Apply

on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: infra 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Apply
        run: |
            terraform apply -auto-approve

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt-get update
          sudo apt-get install gh
    
      - name: Set EC2 Public IP as secret
        run: |
           terraform output -raw ec2_public_ip
           terraform output -raw s3_bucket_name
           terraform output -raw iam_access_key_id
           terraform output -raw iam_secret_access_key
           gh secret set EC2_PUBLIC_IP -b"$(terraform output -raw ec2_public_ip)"
           gh secret set S3_BUCKET_NAME -b"$(terraform output -raw s3_bucket_name)"
           gh secret set IAM_ACCESS_KEY_ID -b"$(terraform output -raw iam_access_key_id)"
           gh secret set IAM_SECRET_ACCESS_KEY -b"$(terraform output -raw iam_secret_access_key)"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
    
