name: Checkout Main Branch

on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
