name: Checkout Main Branch

on:
  workflow_dispatch:
    inputs:
      refresh_required:
        description: 'Set to true to refresh state'
        type: boolean
        default: false
      import_resources:
        description: 'Set to true to import resources'
        type: boolean
        default: false
      destroy:
        description: "Destroy resources"
        type: boolean
        default: false
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: infra
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        if: github.event.inputs.destroy != 'true'
        run: terraform plan
      - name: Terraform Apply
        if: github.event.inputs.destroy != 'true'
        run: terraform apply -auto-approve
      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve
